### ISSUE TITLE
Deprecated Message

### ISSUE THREAD

**Issue by dodgy99** [deadlydog/VSTS.Wait#2]
Hi,

When using in an AzureDevops release pipeline we get the message

##[warning]Task 'Wait' (1.2.3) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

Thanks

**Comment by deadlydog** [comment]
Ok, after a bit of work I got the extension upgraded and this issue is fixed in v1.2.30 of the extension. Thanks.
